# Generated by Django 4.0.6 on 2022-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_agenda_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='ativo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
